// Common
export const REDIRECT = 'REDIRECT';
export const SET_API_STATUS = 'SET_API_STATUS';

// Auth actions
export const AUTHENTICATE_SESSION = 'AUTHENTICATE_SESSION';
export const LOGIN = 'LOGIN';
export const LOGOUT = 'LOGOUT';
export const REFRESH_SESSION = 'REFRESH_SESSION';
export const SET_LOGIN_STATUS = 'SET_LOGIN_STATUS';
export const SET_AUTH_API_STATUS = 'SET_AUTH_API_STATUS';
export const SET_USER_DETAILS = 'SET_USER_DETAILS';
export const VALIDATE_PASSWORD_RESET_LINK = 'VALIDATE_PASSWORD_RESET_LINK';
export const SET_VALIDITY = 'SET_VALIDITY';
export const TOGGLE_RESET_PASSWORD_DONE = 'TOGGLE_RESET_PASSWORD_DONE';

// Uploads Actions
export const SHOW_MORE_UPLOADS = 'SHOW_MORE_UPLOADS';
export const SET_PREV_UPLOADS = 'SET_PREV_UPLOADS';
export const SET_CURR_SELECTED_UPLOAD = 'SET_CURR_SELECTED_UPLOAD';
export const UPDATE_CURR_SELECTED_UPLOAD = 'UPDATE_CURR_SELECTED_UPLOAD';
export const SET_CURR_PAGE = 'SET_CURR_PAGE';
export const GET_TEMPLATE_OPTIONS = 'GET_TEMPLATE_OPTIONS';
export const SET_TEMPLATE_OPTIONS = 'SET_TEMPLATE_OPTIONS';
export const GET_FILE_DATA = 'GET_FILE_DATA';
export const SET_FILE_DATA = 'SET_FILE_DATA';
export const SET_LOADING = 'SET_LOADING';
export const SET_UPLOADS_API_STATUS = 'SET_UPLOADS_API_STATUS';

// File Actions
export const SET_TEMPLATE = 'SET_TEMPLATE';
export const SET_TEMPLATE_VERSION = 'SET_TEMPLATE_VERSION';
export const SET_FILE_IMPORT_API_STATUS = 'SET_FILE_IMPORT_API_STATUS';
export const SET_FILE_NAME = 'SET_FILE_NAME';
export const TOGGLE_MODAL = 'TOGGLE_MODAL';
export const UPLOAD_FILE = 'UPLOAD_FILE';
export const UPLOAD_FILE_FORCED = 'UPLOAD_FILE_FORCED';
export const SET_VALIDATION_ERROR = 'SET_VALIDATION_ERROR';

// Forgot Password Actions
export const TOGGLE_FORGOT_PASSWORD_WINDOW = 'TOGGLE_FORGOT_PASSWORD_WINDOW';
export const SET_FORGOT_PASSWORD_EMAIL = 'SET_FORGOT_PASSWORD_EMAIL';
export const SEND_PASSWORD_RESET_EMAIL = 'SEND_PASSWORD_RESET_EMAIL';
export const CHANGE_RESET_PASSWORD = 'CHANGE_RESET_PASSWORD';
export const RESET_PASSWORD = 'RESET_PASSWORD';
export const CHANGE_CONFIRM_RESET_PASSWORD = 'CHANGE_CONFIRM_RESET_PASSWORD';

// Views Actions
export const UPDATE_LAYOUT = 'UPDATE_LAYOUT';
export const GET_VIEWS_DATA = 'GET_VIEWS_DATA';
export const SET_VIEWS_DATA = 'SET_VIEWS_DATA';
export const SET_CURR_VIEW = 'SET_CURR_VIEW_ID';

// REPORTS ACTIONS
export const GET_REPORTS_DATA_BY_ID = 'GET_REPORTS_DATA_BY_ID';
export const INITIALIZE_REPORTS_FILTERS = 'INITIALIZE_REPORTS_FILTERS';
export const SET_REPORTS_FILTERS = 'SET_REPORTS_FILTERS';
export const UPDATE_REPORTS_FILTER_VALUE = 'UPDATE_REPORTS_FILTER_VALUE';
export const SET_REPORTS_DATA_IN_REDUCER = 'SET_REPORTS_DATA_IN_REDUCER';
export const SET_REPORTS_POINT_IN_TIME_STATUS = 'SET_REPORTS_POINT_IN_TIME_STATUS';
export const SET_REPORTS_API_STATUS = 'SET_REPORTS_API_STATUS';
export const GET_ROW_CLICK_DATA = 'GET_ROW_CLICK_DATA';
export const SET_ROW_CLICK_DATA = 'SET_ROW_CLICK_DATA';

export const UPDATE_ASSUMPTIONS = 'UPDATE_ASSUMPTIONS';

// MODELS ACTIONS
export const GET_MODELS_DATA_BY_ID = 'GET_MODELS_DATA_BY_ID';
export const SET_MODELS_DATA_IN_REDUCER = 'SET_MODELS_DATA_IN_REDUCER';

// DASHBOARD ACTIONS
export const GET_DASHBOARD_DATA = 'GET_DASHBOARD_DATA';
export const SET_DASHBOARD_DATA = 'SET_DASHBOARD_DATA';
export const SET_FILTERS = 'SET_FILTERS';
export const CHANGE_FILTER_VALUE = 'CHANGE_FILTER_VALUE';
export const VIEW_POINT_IN_TIME = 'VIEW_POINT_IN_TIME';
export const SET_DASHBOARD_API_STATUS = 'SET_DASHBOARD_API_STATUS';
export const SET_POINT_IN_TIME_STATUS = 'SET_POINT_IN_TIME_STATUS';

// ANALYTICS ACTIONS
export const SEND_ANALYTICS = 'SEND_ANALYTICS';

// PLANNING ACTIONS
export const SET_EDITABLE_PARAMS = 'SET_EDITABLE_PARAMS';
export const SAVE_DATA = 'SAVE_DATA';
export const SET_PLANNING_DATA = 'SET_PLANNING_DATA';

// METADATA ACTIONS
export const SET_METADATA = 'SET_METADATA';
export const GET_METADATA = 'GET_METADATA';

export const UPDATE_CURRENCY_RATES = 'UPDATE_CURRENCY_RATES';
