export const FETCHING_VIEWS_LIST = 'FETCHING_VIEWS_LIST';
export const FETCHING_VIEWS_LIST_FAILED = 'FETCHING_VIEWS_LIST_FAILED';

export const FETCHING_DASHBOARD_DATA = 'FETCHING_DASHBOARD_DATA';
export const FETCHING_DASHBOARD_DATA_FAILED = 'FETCHING_DASHBOARD_DATA_FAILED';

export const FETCHING_REPORTS_DATA = 'FETCHING_REPORTS_DATA';
export const FETCHING_REPORTS_DATA_FAILED = 'FETCHING_REPORTS_DATA_FAILED';

export const UPLOADING_FILE = 'UPLOADING_FILE';
export const UPLOADING_FILE_FAILED = 'UPLOADING_FILE_FAILED';

export const FETCHING_TEMPLATES = 'FETCHING_TEMPLATES';
export const FETCHING_TEMPLATES_FAILED = 'FETCHING_TEMPLATES_FAILED';

export const FETCHING_PREVIOUS_UPLOADS = 'FETCHING_PREVIOUS_UPLOADS';
export const FETCHING_PREVIOUS_UPLOADS_FAILED = 'FETCHING_PREVIOUS_UPLOADS_FAILED';

export const LOGGING_IN = 'LOGGING_IN';
export const LOGIN_FAILED = 'LOGGING_IN';

export const LOGGING_OUT = 'LOGGING_OUT';
export const LOGOUT_FAILED = 'LOGOUT_FAILED';
export const SENDING_EMAIL = 'SENDING_EMAIL';
export const SENDING_EMAIL_FAILED = 'SENDING_EMAIL_FAILED';
export const SENDING_EMAIL_SUCCESS = 'SENDING_EMAIL_SUCCESS';

export const API_SUCCESS = 'API_SUCCESS';
export const API_FAILED = 'API_FAILED';
export const API_IN_PROGRESS = 'API_IN_PROGRESS';
