const viewsList = [
	{
		privilege_id: 1,
		object_type: 'view',
		view_id: 1,
		view_type: 'dashboard',
		action: 'READ',
		filters: [
			{
				filter_id: 4,
				allowed_values: [
					{
						name: 'Sep 2021',
						startDate: '20220901',
						endDate: '20221001',
						asof: '20221001'
					},
					{
						name: 'Oct 2021',
						startDate: '20221001',
						endDate: '20221101',
						asof: '20221101'
					},
					{
						name: 'Nov 2021',
						startDate: '20221101',
						endDate: '20221201',
						asof: '20221201'
					},
					{
						name: 'Dec 2021',
						startDate: '20221201',
						endDate: '20230101',
						asof: '20230101'
					}
				],
				min: null,
				max: null,
				filter_type: 'drop-down',
				filter_name: 'month',
				default_value: 'Sep 2021'
			},
			{
				filter_id: 1,
				allowed_values: ['NA', 'SEA', 'MEA', 'APJ', 'India and Subcontinent'],
				min: null,
				max: null,
				filter_type: 'drop-down',
				filter_name: 'region',
				default_value: 'NA'
			},
			{
				filter_id: 2,
				allowed_values: ['Enterprise', 'SME typ'],
				min: null,
				max: null,
				filter_type: 'drop-down',
				filter_name: 'type',
				default_value: null
			},
			{
				filter_id: 3,
				allowed_values: [
					'Retail',
					'E-commerce',
					'Manufacturing & CPG/FMCG',
					'Industrial Services',
					'3PL & CEP',
					'E-grocery',
					'Others',
					'Home Services'
				],
				min: null,
				max: null,
				filter_type: 'drop-down',
				filter_name: 'industry',
				default_value: null
			}
		],
		config: {
			customer: 'Alex Cross',
			items: {
				product: 'Tea',
				qty: 6
			}
		},
		object_id: 1,
		view_name: 'Sample Dashboard 1'
	},
	{
		privilege_id: 2,
		object_type: 'view',
		view_id: 2,
		view_type: 'report',
		action: 'READ',
		filters: [
			{
				filter_id: 4,
				allowed_values: [
					{
						name: 'Sep 2021',
						startDate: '20220901',
						endDate: '20221001',
						asof: '20221001'
					},
					{
						name: 'Oct 2021',
						startDate: '20221001',
						endDate: '20221101',
						asof: '20221101'
					},
					{
						name: 'Nov 2021',
						startDate: '20221101',
						endDate: '20221201',
						asof: '20221201'
					},
					{
						name: 'Dec 2021',
						startDate: '20221201',
						endDate: '20230101',
						asof: '20230101'
					}
				],
				min: null,
				max: null,
				filter_type: 'drop-down',
				filter_name: 'month',
				default_value: 'Sep 2021'
			},
			{
				filter_id: 1,
				allowed_values: ['NA', 'SEA', 'MEA', 'APJ', 'India and Subcontinent'],
				min: null,
				max: null,
				filter_type: 'drop-down',
				filter_name: 'region',
				default_value: 'NA'
			},
			{
				filter_id: 2,
				allowed_values: ['Enterprise', 'SME typ'],
				min: null,
				max: null,
				filter_type: 'drop-down',
				filter_name: 'type',
				default_value: null
			},
			{
				filter_id: 3,
				allowed_values: [
					'Retail',
					'E-commerce',
					'Manufacturing & CPG/FMCG',
					'Industrial Services',
					'3PL & CEP',
					'E-grocery',
					'Others',
					'Home Services'
				],
				min: null,
				max: null,
				filter_type: 'drop-down',
				filter_name: 'industry',
				default_value: null
			}
		],
		config: {
			customer: 'Alex Cross',
			items: {
				product: 'Tea',
				qty: 6
			}
		},
		object_id: 2,
		view_name: 'Sample Report'
	},
	{
		privilege_id: 3,
		object_type: 'view',
		view_id: 3,
		view_type: 'dashboard',
		action: 'READ',
		filters: [
			{
				filter_id: 1,
				allowed_values: ['NA', 'SEA', 'MEA', 'APJ', 'India and Subcontinent'],
				min: null,
				max: null,
				filter_type: 'drop-down',
				filter_name: 'region',
				default_value: 'NA'
			},
			{
				filter_id: 2,
				allowed_values: ['Enterprise', 'SME typ'],
				min: null,
				max: null,
				filter_type: 'drop-down',
				filter_name: 'type',
				default_value: null
			},
			{
				filter_id: 3,
				allowed_values: [
					'Retail',
					'E-commerce',
					'Manufacturing & CPG/FMCG',
					'Industrial Services',
					'3PL & CEP',
					'E-grocery',
					'Others',
					'Home Services'
				],
				min: null,
				max: null,
				filter_type: 'drop-down',
				filter_name: 'industry',
				default_value: null
			},
			{
				filter_id: 4,
				allowed_values: [
					{
						name: 'Sep 2021',
						startDate: '20220901',
						endDate: '20221001',
						asof: '20221001'
					},
					{
						name: 'Oct 2021',
						startDate: '20221001',
						endDate: '20221101',
						asof: '20221101'
					},
					{
						name: 'Nov 2021',
						startDate: '20221101',
						endDate: '20221201',
						asof: '20221201'
					},
					{
						name: 'Dec 2021',
						startDate: '20221201',
						endDate: '20230101',
						asof: '20230101'
					}
				],
				min: null,
				max: null,
				filter_type: 'drop-down',
				filter_name: 'month',
				default_value: 'Sep 2021'
			}
		],
		config: {
			customer: 'Alex Cross',
			items: {
				product: 'Tea',
				qty: 6
			}
		},
		object_id: 3,
		view_name: 'Sampled Dashboard 2'
	}
];

export const dashboard1 = {
	view_layout: [
		{
			component_type: 'grid',
			component_id: 1,
			component_config: {
				background: '#FFFFFF',
				connectedReportId: 1,
				hoverText: 'ARPA = ARR live / Total customers'
			},
			component_name: 'Sample Grid',
			component_data: [
				{
					id: 1,
					Segment: 'Channel Partners',
					Country: 'Germany',
					Product: ' VTT ',
					'Discount Band': ' None ',
					'Units Sold': '2838',
					'Manufacturing Price': ' $                250.00 ',
					'Sale Price': ' $              12.00 ',
					'Gross Sales': ' $          34,056.00 ',
					Discounts: ' $                     -   ',
					Sales: ' $                  34,056.00 ',
					COGS: ' $     8,514.00 ',
					Profit: ' $                    25,542.00 ',
					Date: '4/1/14',
					'Month Number': '4',
					'Month Name': ' April ',
					Year: '2014'
				},
				{
					id: 2,
					Segment: 'Midmarket',
					Country: 'France',
					Product: ' VTT ',
					'Discount Band': ' None ',
					'Units Sold': '2178',
					'Manufacturing Price': ' $                250.00 ',
					'Sale Price': ' $              15.00 ',
					'Gross Sales': ' $          32,670.00 ',
					Discounts: ' $                     -   ',
					Sales: ' $                  32,670.00 ',
					COGS: ' $   21,780.00 ',
					Profit: ' $                    10,890.00 ',
					Date: '6/1/14',
					'Month Number': '6',
					'Month Name': ' June ',
					Year: '2014'
				},
				{
					id: 3,
					Segment: 'Midmarket',
					Country: 'Germany',
					Product: ' VTT ',
					'Discount Band': ' None ',
					'Units Sold': '888',
					'Manufacturing Price': ' $                250.00 ',
					'Sale Price': ' $              15.00 ',
					'Gross Sales': ' $          13,320.00 ',
					Discounts: ' $                     -   ',
					Sales: ' $                  13,320.00 ',
					COGS: ' $     8,880.00 ',
					Profit: ' $                       4,440.00 ',
					Date: '6/1/14',
					'Month Number': '6',
					'Month Name': ' June ',
					Year: '2014'
				},
				{
					id: 4,
					Segment: 'Government',
					Country: 'France',
					Product: ' VTT ',
					'Discount Band': ' None ',
					'Units Sold': '1527',
					'Manufacturing Price': ' $                250.00 ',
					'Sale Price': ' $           350.00 ',
					'Gross Sales': ' $      5,34,450.00 ',
					Discounts: ' $                     -   ',
					Sales: ' $               5,34,450.00 ',
					COGS: '',
					Profit: ' $                 1,37,430.00 ',
					Date: '9/1/13',
					'Month Number': '9',
					'Month Name': ' September ',
					Year: '2013'
				},
				{
					id: 5,
					Segment: 'Small Business',
					Country: 'France',
					Product: ' VTT ',
					'Discount Band': ' None ',
					'Units Sold': '2151',
					'Manufacturing Price': ' $                250.00 ',
					'Sale Price': ' $           300.00 ',
					'Gross Sales': ' $      6,45,300.00 ',
					Discounts: ' $                     -   ',
					Sales: ' $               6,45,300.00 ',
					COGS: '',
					Profit: ' $                 1,07,550.00 ',
					Date: '9/1/14',
					'Month Number': '9',
					'Month Name': ' September ',
					Year: '2014'
				},
				{
					id: 6,
					Segment: 'Government',
					Country: 'Canada',
					Product: ' VTT ',
					'Discount Band': ' None ',
					'Units Sold': '1817',
					'Manufacturing Price': ' $                250.00 ',
					'Sale Price': ' $              20.00 ',
					'Gross Sales': ' $          36,340.00 ',
					Discounts: ' $                     -   ',
					Sales: ' $                  36,340.00 ',
					COGS: ' $   18,170.00 ',
					Profit: ' $                    18,170.00 ',
					Date: '12/1/14',
					'Month Number': '12',
					'Month Name': ' December ',
					Year: '2014'
				},
				{
					id: 7,
					Segment: 'Government',
					Country: 'France',
					Product: ' Amarilla ',
					'Discount Band': ' None ',
					'Units Sold': '2750',
					'Manufacturing Price': ' $                260.00 ',
					'Sale Price': ' $           350.00 ',
					'Gross Sales': ' $      9,62,500.00 ',
					Discounts: ' $                     -   ',
					Sales: ' $               9,62,500.00 ',
					COGS: '',
					Profit: ' $                 2,47,500.00 ',
					Date: '2/1/14',
					'Month Number': '2',
					'Month Name': ' February ',
					Year: '2014'
				},
				{
					id: 8,
					Segment: 'Channel Partners',
					Country: 'United States of America',
					Product: ' Amarilla ',
					'Discount Band': ' None ',
					'Units Sold': '1953',
					'Manufacturing Price': ' $                260.00 ',
					'Sale Price': ' $              12.00 ',
					'Gross Sales': ' $          23,436.00 ',
					Discounts: ' $                     -   ',
					Sales: ' $                  23,436.00 ',
					COGS: ' $     5,859.00 ',
					Profit: ' $                    17,577.00 ',
					Date: '4/1/14',
					'Month Number': '4',
					'Month Name': ' April ',
					Year: '2014'
				},
				{
					id: 9,
					Segment: 'Enterprise',
					Country: 'Germany',
					Product: ' Amarilla ',
					'Discount Band': ' None ',
					'Units Sold': '4219.5',
					'Manufacturing Price': ' $                260.00 ',
					'Sale Price': ' $           125.00 ',
					'Gross Sales': ' $      5,27,437.50 ',
					Discounts: ' $                     -   ',
					Sales: ' $               5,27,437.50 ',
					COGS: '',
					Profit: ' $                    21,097.50 ',
					Date: '4/1/14',
					'Month Number': '4',
					'Month Name': ' April ',
					Year: '2014'
				},
				{
					id: 10,
					Segment: 'Government',
					Country: 'France',
					Product: ' Amarilla ',
					'Discount Band': ' None ',
					'Units Sold': '1899',
					'Manufacturing Price': ' $                260.00 ',
					'Sale Price': ' $              20.00 ',
					'Gross Sales': ' $          37,980.00 ',
					Discounts: ' $                     -   ',
					Sales: ' $                  37,980.00 ',
					COGS: ' $   18,990.00 ',
					Profit: ' $                    18,990.00 ',
					Date: '6/1/14',
					'Month Number': '6',
					'Month Name': ' June ',
					Year: '2014'
				},
				{
					id: 11,
					Segment: 'Government',
					Country: 'Germany',
					Product: ' Amarilla ',
					'Discount Band': ' None ',
					'Units Sold': '1686',
					'Manufacturing Price': ' $                260.00 ',
					'Sale Price': ' $                7.00 ',
					'Gross Sales': ' $          11,802.00 ',
					Discounts: ' $                     -   ',
					Sales: ' $                  11,802.00 ',
					COGS: ' $     8,430.00 ',
					Profit: ' $                       3,372.00 ',
					Date: '7/1/14',
					'Month Number': '7',
					'Month Name': ' July ',
					Year: '2014'
				},
				{
					id: 12,
					Segment: 'Channel Partners',
					Country: 'United States of America',
					Product: ' Amarilla ',
					'Discount Band': ' None ',
					'Units Sold': '2141',
					'Manufacturing Price': ' $                260.00 ',
					'Sale Price': ' $              12.00 ',
					'Gross Sales': ' $          25,692.00 ',
					Discounts: ' $                     -   ',
					Sales: ' $                  25,692.00 ',
					COGS: ' $     6,423.00 ',
					Profit: ' $                    19,269.00 ',
					Date: '8/1/14',
					'Month Number': '8',
					'Month Name': ' August ',
					Year: '2014'
				},
				{
					id: 13,
					Segment: 'Government',
					Country: 'United States of America',
					Product: ' Amarilla ',
					'Discount Band': ' None ',
					'Units Sold': '1143',
					'Manufacturing Price': ' $                260.00 ',
					'Sale Price': ' $                7.00 ',
					'Gross Sales': ' $            8,001.00 ',
					Discounts: ' $                     -   ',
					Sales: ' $                     8,001.00 ',
					COGS: ' $     5,715.00 ',
					Profit: ' $                       2,286.00 ',
					Date: '10/1/14',
					'Month Number': '10',
					'Month Name': ' October ',
					Year: '2014'
				},
				{
					id: 14,
					Segment: 'Midmarket',
					Country: 'United States of America',
					Product: ' Amarilla ',
					'Discount Band': ' None ',
					'Units Sold': '615',
					'Manufacturing Price': ' $                260.00 ',
					'Sale Price': ' $              15.00 ',
					'Gross Sales': ' $            9,225.00 ',
					Discounts: ' $                     -   ',
					Sales: ' $                     9,225.00 ',
					COGS: ' $     6,150.00 ',
					Profit: ' $                       3,075.00 ',
					Date: '12/1/14',
					'Month Number': '12',
					'Month Name': ' December ',
					Year: '2014'
				},
				{
					id: 15,
					Segment: 'Government',
					Country: 'France',
					Product: ' Paseo ',
					'Discount Band': ' Low ',
					'Units Sold': '3945',
					'Manufacturing Price': ' $                  10.00 ',
					'Sale Price': ' $                7.00 ',
					'Gross Sales': ' $          27,615.00 ',
					Discounts: ' $           276.15 ',
					Sales: ' $                  27,338.85 ',
					COGS: ' $   19,725.00 ',
					Profit: ' $                       7,613.85 ',
					Date: '1/1/14',
					'Month Number': '1',
					'Month Name': ' January ',
					Year: '2014'
				},
				{
					id: 16,
					Segment: 'Midmarket',
					Country: 'France',
					Product: ' Paseo ',
					'Discount Band': ' Low ',
					'Units Sold': '2296',
					'Manufacturing Price': ' $                  10.00 ',
					'Sale Price': ' $              15.00 ',
					'Gross Sales': ' $          34,440.00 ',
					Discounts: ' $           344.40 ',
					Sales: ' $                  34,095.60 ',
					COGS: ' $   22,960.00 ',
					Profit: ' $                    11,135.60 ',
					Date: '2/1/14',
					'Month Number': '2',
					'Month Name': ' February ',
					Year: '2014'
				},
				{
					id: 17,
					Segment: 'Government',
					Country: 'France',
					Product: ' Paseo ',
					'Discount Band': ' Low ',
					'Units Sold': '1030',
					'Manufacturing Price': ' $                  10.00 ',
					'Sale Price': ' $                7.00 ',
					'Gross Sales': ' $            7,210.00 ',
					Discounts: ' $              72.10 ',
					Sales: ' $                     7,137.90 ',
					COGS: ' $     5,150.00 ',
					Profit: ' $                       1,987.90 ',
					Date: '5/1/14',
					'Month Number': '5',
					'Month Name': ' May ',
					Year: '2014'
				},
				{
					id: 18,
					Segment: 'Government',
					Country: 'France',
					Product: ' Velo ',
					'Discount Band': ' Low ',
					'Units Sold': '639',
					'Manufacturing Price': ' $                120.00 ',
					'Sale Price': ' $                7.00 ',
					'Gross Sales': ' $            4,473.00 ',
					Discounts: ' $              44.73 ',
					Sales: ' $                     4,428.27 ',
					COGS: ' $     3,195.00 ',
					Profit: ' $                       1,233.27 ',
					Date: '11/1/14',
					'Month Number': '11',
					'Month Name': ' November ',
					Year: '2014'
				},
				{
					id: 19,
					Segment: 'Government',
					Country: 'Canada',
					Product: ' VTT ',
					'Discount Band': ' Low ',
					'Units Sold': '1326',
					'Manufacturing Price': ' $                250.00 ',
					'Sale Price': ' $                7.00 ',
					'Gross Sales': ' $            9,282.00 ',
					Discounts: ' $              92.82 ',
					Sales: ' $                     9,189.18 ',
					COGS: ' $     6,630.00 ',
					Profit: ' $                       2,559.18 ',
					Date: '3/1/14',
					'Month Number': '3',
					'Month Name': ' March ',
					Year: '2014'
				},
				{
					id: 20,
					Segment: 'Channel Partners',
					Country: 'United States of America',
					Product: ' Carretera ',
					'Discount Band': ' Low ',
					'Units Sold': '1858',
					'Manufacturing Price': ' $                     3.00 ',
					'Sale Price': ' $              12.00 ',
					'Gross Sales': ' $          22,296.00 ',
					Discounts: ' $           222.96 ',
					Sales: ' $                  22,073.04 ',
					COGS: ' $     5,574.00 ',
					Profit: ' $                    16,499.04 ',
					Date: '2/1/14',
					'Month Number': '2',
					'Month Name': ' February ',
					Year: '2014'
				},
				{
					id: 21,
					Segment: 'Government',
					Country: 'Mexico',
					Product: ' Carretera ',
					'Discount Band': ' Low ',
					'Units Sold': '1210',
					'Manufacturing Price': ' $                     3.00 ',
					'Sale Price': ' $           350.00 ',
					'Gross Sales': ' $      4,23,500.00 ',
					Discounts: ' $        4,235.00 ',
					Sales: ' $               4,19,265.00 ',
					COGS: '',
					Profit: ' $                 1,04,665.00 ',
					Date: '3/1/14',
					'Month Number': '3',
					'Month Name': ' March ',
					Year: '2014'
				},
				{
					id: 22,
					Segment: 'Government',
					Country: 'United States of America',
					Product: ' Carretera ',
					'Discount Band': ' Low ',
					'Units Sold': '2529',
					'Manufacturing Price': ' $                     3.00 ',
					'Sale Price': ' $                7.00 ',
					'Gross Sales': ' $          17,703.00 ',
					Discounts: ' $           177.03 ',
					Sales: ' $                  17,525.97 ',
					COGS: ' $   12,645.00 ',
					Profit: ' $                       4,880.97 ',
					Date: '7/1/14',
					'Month Number': '7',
					'Month Name': ' July ',
					Year: '2014'
				},
				{
					id: 23,
					Segment: 'Channel Partners',
					Country: 'Canada',
					Product: ' Carretera ',
					'Discount Band': ' Low ',
					'Units Sold': '1445',
					'Manufacturing Price': ' $                     3.00 ',
					'Sale Price': ' $              12.00 ',
					'Gross Sales': ' $          17,340.00 ',
					Discounts: ' $           173.40 ',
					Sales: ' $                  17,166.60 ',
					COGS: ' $     4,335.00 ',
					Profit: ' $                    12,831.60 ',
					Date: '9/1/14',
					'Month Number': '9',
					'Month Name': ' September ',
					Year: '2014'
				},
				{
					id: 24,
					Segment: 'Enterprise',
					Country: 'United States of America',
					Product: ' Carretera ',
					'Discount Band': ' Low ',
					'Units Sold': '330',
					'Manufacturing Price': ' $                     3.00 ',
					'Sale Price': ' $           125.00 ',
					'Gross Sales': ' $          41,250.00 ',
					Discounts: ' $           412.50 ',
					Sales: ' $                  40,837.50 ',
					COGS: ' $   39,600.00 ',
					Profit: ' $                       1,237.50 ',
					Date: '9/1/13',
					'Month Number': '9',
					'Month Name': ' September ',
					Year: '2013'
				},
				{
					id: 25,
					Segment: 'Channel Partners',
					Country: 'France',
					Product: ' Carretera ',
					'Discount Band': ' Low ',
					'Units Sold': '2671',
					'Manufacturing Price': ' $                     3.00 ',
					'Sale Price': ' $              12.00 ',
					'Gross Sales': ' $          32,052.00 ',
					Discounts: ' $           320.52 ',
					Sales: ' $                  31,731.48 ',
					COGS: ' $     8,013.00 ',
					Profit: ' $                    23,718.48 ',
					Date: '9/1/14',
					'Month Number': '9',
					'Month Name': ' September ',
					Year: '2014'
				},
				{
					id: 26,
					Segment: 'Channel Partners',
					Country: 'Germany',
					Product: ' Carretera ',
					'Discount Band': ' Low ',
					'Units Sold': '766',
					'Manufacturing Price': ' $                     3.00 ',
					'Sale Price': ' $              12.00 ',
					'Gross Sales': ' $            9,192.00 ',
					Discounts: ' $              91.92 ',
					Sales: ' $                     9,100.08 ',
					COGS: ' $     2,298.00 ',
					Profit: ' $                       6,802.08 ',
					Date: '10/1/13',
					'Month Number': '10',
					'Month Name': ' October ',
					Year: '2013'
				},
				{
					id: 27,
					Segment: 'Small Business',
					Country: 'Mexico',
					Product: ' Carretera ',
					'Discount Band': ' Low ',
					'Units Sold': '494',
					'Manufacturing Price': ' $                     3.00 ',
					'Sale Price': ' $           300.00 ',
					'Gross Sales': ' $      1,48,200.00 ',
					Discounts: ' $        1,482.00 ',
					Sales: ' $               1,46,718.00 ',
					COGS: '',
					Profit: ' $                    23,218.00 ',
					Date: '10/1/13',
					'Month Number': '10',
					'Month Name': ' October ',
					Year: '2013'
				},
				{
					id: 28,
					Segment: 'Government',
					Country: 'Mexico',
					Product: ' Carretera ',
					'Discount Band': ' Low ',
					'Units Sold': '1397',
					'Manufacturing Price': ' $                     3.00 ',
					'Sale Price': ' $           350.00 ',
					'Gross Sales': ' $      4,88,950.00 ',
					Discounts: ' $        4,889.50 ',
					Sales: ' $               4,84,060.50 ',
					COGS: '',
					Profit: ' $                 1,20,840.50 ',
					Date: '10/1/14',
					'Month Number': '10',
					'Month Name': ' October ',
					Year: '2014'
				},
				{
					id: 29,
					Segment: 'Government',
					Country: 'France',
					Product: ' Carretera ',
					'Discount Band': ' Low ',
					'Units Sold': '2155',
					'Manufacturing Price': ' $                     3.00 ',
					'Sale Price': ' $           350.00 ',
					'Gross Sales': ' $      7,54,250.00 ',
					Discounts: ' $        7,542.50 ',
					Sales: ' $               7,46,707.50 ',
					COGS: '',
					Profit: ' $                 1,86,407.50 ',
					Date: '12/1/14',
					'Month Number': '12',
					'Month Name': ' December ',
					Year: '2014'
				},
				{
					id: 30,
					Segment: 'Midmarket',
					Country: 'Mexico',
					Product: ' Montana ',
					'Discount Band': ' Low ',
					'Units Sold': '2214',
					'Manufacturing Price': ' $                     5.00 ',
					'Sale Price': ' $              15.00 ',
					'Gross Sales': ' $          33,210.00 ',
					Discounts: ' $           332.10 ',
					Sales: ' $                  32,877.90 ',
					COGS: ' $   22,140.00 ',
					Profit: ' $                    10,737.90 ',
					Date: '3/1/14',
					'Month Number': '3',
					'Month Name': ' March ',
					Year: '2014'
				},
				{
					id: 31,
					Segment: 'Small Business',
					Country: 'United States of America',
					Product: ' Montana ',
					'Discount Band': ' Low ',
					'Units Sold': '2301',
					'Manufacturing Price': ' $                     5.00 ',
					'Sale Price': ' $           300.00 ',
					'Gross Sales': ' $      6,90,300.00 ',
					Discounts: ' $        6,903.00 ',
					Sales: ' $               6,83,397.00 ',
					COGS: '',
					Profit: ' $                 1,08,147.00 ',
					Date: '4/1/14',
					'Month Number': '4',
					'Month Name': ' April ',
					Year: '2014'
				},
				{
					id: 32,
					Segment: 'Government',
					Country: 'France',
					Product: ' Montana ',
					'Discount Band': ' Low ',
					'Units Sold': '1375.5',
					'Manufacturing Price': ' $                     5.00 ',
					'Sale Price': ' $              20.00 ',
					'Gross Sales': ' $          27,510.00 ',
					Discounts: ' $           275.10 ',
					Sales: ' $                  27,234.90 ',
					COGS: ' $   13,755.00 ',
					Profit: ' $                    13,479.90 ',
					Date: '7/1/14',
					'Month Number': '7',
					'Month Name': ' July ',
					Year: '2014'
				},
				{
					id: 33,
					Segment: 'Government',
					Country: 'Canada',
					Product: ' Montana ',
					'Discount Band': ' Low ',
					'Units Sold': '1830',
					'Manufacturing Price': ' $                     5.00 ',
					'Sale Price': ' $                7.00 ',
					'Gross Sales': ' $          12,810.00 ',
					Discounts: ' $           128.10 ',
					Sales: ' $                  12,681.90 ',
					COGS: ' $     9,150.00 ',
					Profit: ' $                       3,531.90 ',
					Date: '8/1/14',
					'Month Number': '8',
					'Month Name': ' August ',
					Year: '2014'
				},
				{
					id: 34,
					Segment: 'Small Business',
					Country: 'United States of America',
					Product: ' Montana ',
					'Discount Band': ' Low ',
					'Units Sold': '2498',
					'Manufacturing Price': ' $                     5.00 ',
					'Sale Price': ' $           300.00 ',
					'Gross Sales': ' $      7,49,400.00 ',
					Discounts: ' $        7,494.00 ',
					Sales: ' $               7,41,906.00 ',
					COGS: '',
					Profit: ' $                 1,17,406.00 ',
					Date: '9/1/13',
					'Month Number': '9',
					'Month Name': ' September ',
					Year: '2013'
				},
				{
					id: 35,
					Segment: 'Enterprise',
					Country: 'United States of America',
					Product: ' Montana ',
					'Discount Band': ' Low ',
					'Units Sold': '663',
					'Manufacturing Price': ' $                     5.00 ',
					'Sale Price': ' $           125.00 ',
					'Gross Sales': ' $          82,875.00 ',
					Discounts: ' $           828.75 ',
					Sales: ' $                  82,046.25 ',
					COGS: ' $   79,560.00 ',
					Profit: ' $                       2,486.25 ',
					Date: '10/1/13',
					'Month Number': '10',
					'Month Name': ' October ',
					Year: '2013'
				},
				{
					id: 36,
					Segment: 'Midmarket',
					Country: 'United States of America',
					Product: ' Paseo ',
					'Discount Band': ' Low ',
					'Units Sold': '1514',
					'Manufacturing Price': ' $                  10.00 ',
					'Sale Price': ' $              15.00 ',
					'Gross Sales': ' $          22,710.00 ',
					Discounts: ' $           227.10 ',
					Sales: ' $                  22,482.90 ',
					COGS: ' $   15,140.00 ',
					Profit: ' $                       7,342.90 ',
					Date: '2/1/14',
					'Month Number': '2',
					'Month Name': ' February ',
					Year: '2014'
				},
				{
					id: 37,
					Segment: 'Government',
					Country: 'United States of America',
					Product: ' Paseo ',
					'Discount Band': ' Low ',
					'Units Sold': '4492.5',
					'Manufacturing Price': ' $                  10.00 ',
					'Sale Price': ' $                7.00 ',
					'Gross Sales': ' $          31,447.50 ',
					Discounts: ' $           314.48 ',
					Sales: ' $                  31,133.03 ',
					COGS: ' $   22,462.50 ',
					Profit: ' $                       8,670.53 ',
					Date: '4/1/14',
					'Month Number': '4',
					'Month Name': ' April ',
					Year: '2014'
				},
				{
					id: 38,
					Segment: 'Enterprise',
					Country: 'United States of America',
					Product: ' Paseo ',
					'Discount Band': ' Low ',
					'Units Sold': '727',
					'Manufacturing Price': ' $                  10.00 ',
					'Sale Price': ' $           125.00 ',
					'Gross Sales': ' $          90,875.00 ',
					Discounts: ' $           908.75 ',
					Sales: ' $                  89,966.25 ',
					COGS: ' $   87,240.00 ',
					Profit: ' $                       2,726.25 ',
					Date: '6/1/14',
					'Month Number': '6',
					'Month Name': ' June ',
					Year: '2014'
				},
				{
					id: 39,
					Segment: 'Enterprise',
					Country: 'France',
					Product: ' Paseo ',
					'Discount Band': ' Low ',
					'Units Sold': '787',
					'Manufacturing Price': ' $                  10.00 ',
					'Sale Price': ' $           125.00 ',
					'Gross Sales': ' $          98,375.00 ',
					Discounts: ' $           983.75 ',
					Sales: ' $                  97,391.25 ',
					COGS: ' $   94,440.00 ',
					Profit: ' $                       2,951.25 ',
					Date: '6/1/14',
					'Month Number': '6',
					'Month Name': ' June ',
					Year: '2014'
				},
				{
					id: 40,
					Segment: 'Enterprise',
					Country: 'Mexico',
					Product: ' Paseo ',
					'Discount Band': ' Low ',
					'Units Sold': '1823',
					'Manufacturing Price': ' $                  10.00 ',
					'Sale Price': ' $           125.00 ',
					'Gross Sales': ' $      2,27,875.00 ',
					Discounts: ' $        2,278.75 ',
					Sales: ' $               2,25,596.25 ',
					COGS: '',
					Profit: ' $                       6,836.25 ',
					Date: '7/1/14',
					'Month Number': '7',
					'Month Name': ' July ',
					Year: '2014'
				}
			],
			position: {
				static: false,
				w: 4,
				moved: false,
				h: 5,
				x: 0,
				y: 0,
				i: '1'
			}
		},
		{
			component_type: 'doughnut',
			component_id: 2,
			component_config: {
				background: '#FFFFFF',
				connectedReportId: 1,
				hoverText: 'ARPA = ARR live / Total customers'
			},
			component_name: 'Doughnut',
			component_data: [
				{count: 1, type: '60 to 80%'},
				{count: 12, type: '0 to 20%'},
				{count: 2, type: '40 to 60%'},
				{count: 3, type: '20 to 40%'}
			],
			position: {
				static: false,
				w: 2,
				moved: false,
				h: 5,
				x: 0,
				y: 5,
				i: '2'
			}
		},
		{
			component_type: 'line-chart',
			component_id: 3,
			component_config: {
				background: '#FFFFFF',
				connectedReportId: 1,
				hoverText: 'ARPA = ARR live / Total customers'
			},
			component_name: 'Area Chart',
			component_data: [
				{
					month: 'sep 2022',
					value: 33.34,
					label: 'mea'
				},
				{
					month: 'oct 2022',
					value: 343.34,
					label: 'mea'
				},
				{
					month: 'nov 2022',
					value: 343.34,
					label: 'india'
				},
				{
					month: 'oct 2022',
					value: 33.34,
					label: 'india'
				},
				{
					month: 'dec 2022',
					value: 343.34,
					label: 'mea'
				},
				{
					month: 'sep 2022',
					value: 343.34,
					label: 'india'
				},
				{
					month: 'nov 2022',
					value: 33.34,
					label: 'mea'
				},
				{
					month: 'dec 2022',
					value: 33.34,
					label: 'india'
				}
			],
			position: {
				static: false,
				w: 2,
				moved: false,
				h: 6,
				x: 0,
				y: 10,
				i: '3'
			}
		},
		{
			component_type: 'graph',
			component_id: 4,
			component_config: {
				background: '#FFFFFF',
				connectedReportId: 1,
				hoverText: 'ARPA = ARR live / Total customers'
			},
			component_name: 'Bar Graph',
			component_data: [
				{
					month: 'sep 2022',
					value: 33.34,
					label: 'mea'
				},
				{
					month: 'oct 2022',
					value: 343.34,
					label: 'mea'
				},
				{
					month: 'nov 2022',
					value: 343.34,
					label: 'india'
				},
				{
					month: 'oct 2022',
					value: 33.34,
					label: 'india'
				},
				{
					month: 'dec 2022',
					value: 343.34,
					label: 'mea'
				},
				{
					month: 'sep 2022',
					value: 343.34,
					label: 'india'
				},
				{
					month: 'nov 2022',
					value: 33.34,
					label: 'mea'
				},
				{
					month: 'dec 2022',
					value: 33.34,
					label: 'india'
				}
			],
			position: {
				static: false,
				w: 2,
				moved: false,
				h: 6,
				x: 0,
				y: 16,
				i: '4'
			}
		},
		{
			component_type: 'graph',
			graph_type: 'stacked',
			component_id: 5,
			component_config: {
				background: '#FFFFFF',
				connectedReportId: 1,
				hoverText: 'ARPA = ARR live / Total customers'
			},
			component_name: 'Stacked Bar Graph',
			component_data: [
				{
					'New ARR': 216331.2,
					'Contraction ARR': -1038139.92,
					month: 'March     2022',
					'Expansion ARR': 920932.32,
					'Churn ARR': -5400
				},
				{
					'New ARR': 126180,
					'Contraction ARR': -1518521.76,
					month: 'April     2022',
					'Expansion ARR': 2974225.44,
					'Churn ARR': -80182.8
				},
				{
					'New ARR': 129876,
					'Contraction ARR': -3427511.88,
					month: 'May       2022',
					'Expansion ARR': 317271.24,
					'Churn ARR': -28527.48
				},
				{
					'New ARR': 159986.64,
					'Contraction ARR': -570765.24,
					month: 'June      2022',
					'Expansion ARR': 352336.2,
					'Churn ARR': -54820.56
				},
				{
					'New ARR': 489663.24,
					'Contraction ARR': -600372.72,
					month: 'July      2022',
					'Expansion ARR': 529105.68,
					'Churn ARR': -64100.04
				},
				{
					'New ARR': 213192,
					'Contraction ARR': -1221515.28,
					month: 'August    2022',
					'Expansion ARR': 695326.8,
					'Churn ARR': 0
				},
				{
					'New ARR': 98024.28,
					'Contraction ARR': -1377137.4,
					month: 'September 2022',
					'Expansion ARR': 258145.2,
					'Churn ARR': -57498.48
				}
			],
			position: {
				static: false,
				w: 2,
				moved: false,
				h: 6,
				x: 0,
				y: 16,
				i: '4'
			}
		},
		{
			component_type: 'graph',
			graph_type: 'grouped',
			component_id: 6,
			component_config: {
				background: '#FFFFFF',
				connectedReportId: 1,
				hoverText: 'ARPA = ARR live / Total customers'
			},
			component_name: 'Grouped Bar Graph',
			component_data: [
				{
					'New ARR': 216331.2,
					'Contraction ARR': -1038139.92,
					month: 'March     2022',
					'Expansion ARR': 920932.32,
					'Churn ARR': -5400
				},
				{
					'New ARR': 126180,
					'Contraction ARR': -1518521.76,
					month: 'April     2022',
					'Expansion ARR': 2974225.44,
					'Churn ARR': -80182.8
				},
				{
					'New ARR': 129876,
					'Contraction ARR': -3427511.88,
					month: 'May       2022',
					'Expansion ARR': 317271.24,
					'Churn ARR': -28527.48
				},
				{
					'New ARR': 159986.64,
					'Contraction ARR': -570765.24,
					month: 'June      2022',
					'Expansion ARR': 352336.2,
					'Churn ARR': -54820.56
				},
				{
					'New ARR': 489663.24,
					'Contraction ARR': -600372.72,
					month: 'July      2022',
					'Expansion ARR': 529105.68,
					'Churn ARR': -64100.04
				},
				{
					'New ARR': 213192,
					'Contraction ARR': -1221515.28,
					month: 'August    2022',
					'Expansion ARR': 695326.8,
					'Churn ARR': 0
				},
				{
					'New ARR': 98024.28,
					'Contraction ARR': -1377137.4,
					month: 'September 2022',
					'Expansion ARR': 258145.2,
					'Churn ARR': -57498.48
				}
			],
			position: {
				static: false,
				w: 2,
				moved: false,
				h: 6,
				x: 0,
				y: 16,
				i: '4'
			}
		},
		{
			component_type: 'funnel',
			component_id: 7,
			component_config: {
				background: '#FFFFFF',
				connectedReportId: 1,
				hoverText: 'ARPA = ARR live / Total customers'
			},
			component_name: 'Funnel Graph',
			component_data: [
				{x: 'Awareness', value: 252},
				{x: 'Interest', value: 105},
				{x: 'Consideration', value: 84},
				{x: 'Evaluation', value: 72},
				{x: 'Commitment', value: 19},
				{x: 'Pre-sale', value: 0},
				{x: 'Sale', value: 10}
			],
			position: {
				static: false,
				w: 2,
				moved: false,
				h: 6,
				x: 0,
				y: 16,
				i: '4'
			}
		}
	],
	type_id: 3,
	name: 'Moengage Dashboard',
	id: 1,
	filters: [
		{
			filter_id: 4,
			allowed_values: [
				{
					name: 'Sep 2021',
					startDate: '20220901',
					endDate: '20221001',
					asof: '20221001'
				},
				{
					name: 'Oct 2021',
					startDate: '20221001',
					endDate: '20221101',
					asof: '20221101'
				},
				{
					name: 'Nov 2021',
					startDate: '20221101',
					endDate: '20221201',
					asof: '20221201'
				},
				{
					name: 'Dec 2021',
					startDate: '20221201',
					endDate: '20230101',
					asof: '20230101'
				}
			],
			min: null,
			max: null,
			filter_type: 'drop-down',
			filter_name: 'month',
			default_value: 'Sep 2021'
		},
		{
			filter_id: 1,
			allowed_values: ['NA', 'SEA', 'MEA', 'APJ', 'India and Subcontinent'],
			min: null,
			max: null,
			filter_type: 'drop-down',
			filter_name: 'region',
			default_value: 'NA'
		},
		{
			filter_id: 2,
			allowed_values: ['Enterprise', 'SME typ'],
			min: null,
			max: null,
			filter_type: 'drop-down',
			filter_name: 'type',
			default_value: null
		},
		{
			filter_id: 3,
			allowed_values: [
				'Retail',
				'E-commerce',
				'Manufacturing & CPG/FMCG',
				'Industrial Services',
				'3PL & CEP',
				'E-grocery',
				'Others',
				'Home Services'
			],
			min: null,
			max: null,
			filter_type: 'drop-down',
			filter_name: 'industry',
			default_value: null
		}
	],
	type: 'dashboard',
	object_id: 1,
	config: {
		customer: 'Alex Cross',
		items: {
			product: 'Tea',
			qty: 6
		}
	}
};

const report1 = {
	view_layout: [
		{
			component_type: 'grid',
			component_id: 1,
			component_config: {
				background: '#FFFFFF',
				connectedReportId: 1,
				hoverText: 'ARPA = ARR live / Total customers'
			},
			component_name: 'component1',
			component_data: [
				{
					id: 1,
					Segment: 'Channel Partners',
					Country: 'Germany',
					Product: ' VTT ',
					'Discount Band': ' None ',
					'Units Sold': '2838',
					'Manufacturing Price': ' $                250.00 ',
					'Sale Price': ' $              12.00 ',
					'Gross Sales': ' $          34,056.00 ',
					Discounts: ' $                     -   ',
					Sales: ' $                  34,056.00 ',
					COGS: ' $     8,514.00 ',
					Profit: ' $                    25,542.00 ',
					Date: '4/1/14',
					'Month Number': '4',
					'Month Name': ' April ',
					Year: '2014'
				},
				{
					id: 2,
					Segment: 'Midmarket',
					Country: 'France',
					Product: ' VTT ',
					'Discount Band': ' None ',
					'Units Sold': '2178',
					'Manufacturing Price': ' $                250.00 ',
					'Sale Price': ' $              15.00 ',
					'Gross Sales': ' $          32,670.00 ',
					Discounts: ' $                     -   ',
					Sales: ' $                  32,670.00 ',
					COGS: ' $   21,780.00 ',
					Profit: ' $                    10,890.00 ',
					Date: '6/1/14',
					'Month Number': '6',
					'Month Name': ' June ',
					Year: '2014'
				},
				{
					id: 3,
					Segment: 'Midmarket',
					Country: 'Germany',
					Product: ' VTT ',
					'Discount Band': ' None ',
					'Units Sold': '888',
					'Manufacturing Price': ' $                250.00 ',
					'Sale Price': ' $              15.00 ',
					'Gross Sales': ' $          13,320.00 ',
					Discounts: ' $                     -   ',
					Sales: ' $                  13,320.00 ',
					COGS: ' $     8,880.00 ',
					Profit: ' $                       4,440.00 ',
					Date: '6/1/14',
					'Month Number': '6',
					'Month Name': ' June ',
					Year: '2014'
				},
				{
					id: 4,
					Segment: 'Government',
					Country: 'France',
					Product: ' VTT ',
					'Discount Band': ' None ',
					'Units Sold': '1527',
					'Manufacturing Price': ' $                250.00 ',
					'Sale Price': ' $           350.00 ',
					'Gross Sales': ' $      5,34,450.00 ',
					Discounts: ' $                     -   ',
					Sales: ' $               5,34,450.00 ',
					COGS: '',
					Profit: ' $                 1,37,430.00 ',
					Date: '9/1/13',
					'Month Number': '9',
					'Month Name': ' September ',
					Year: '2013'
				},
				{
					id: 5,
					Segment: 'Small Business',
					Country: 'France',
					Product: ' VTT ',
					'Discount Band': ' None ',
					'Units Sold': '2151',
					'Manufacturing Price': ' $                250.00 ',
					'Sale Price': ' $           300.00 ',
					'Gross Sales': ' $      6,45,300.00 ',
					Discounts: ' $                     -   ',
					Sales: ' $               6,45,300.00 ',
					COGS: '',
					Profit: ' $                 1,07,550.00 ',
					Date: '9/1/14',
					'Month Number': '9',
					'Month Name': ' September ',
					Year: '2014'
				},
				{
					id: 6,
					Segment: 'Government',
					Country: 'Canada',
					Product: ' VTT ',
					'Discount Band': ' None ',
					'Units Sold': '1817',
					'Manufacturing Price': ' $                250.00 ',
					'Sale Price': ' $              20.00 ',
					'Gross Sales': ' $          36,340.00 ',
					Discounts: ' $                     -   ',
					Sales: ' $                  36,340.00 ',
					COGS: ' $   18,170.00 ',
					Profit: ' $                    18,170.00 ',
					Date: '12/1/14',
					'Month Number': '12',
					'Month Name': ' December ',
					Year: '2014'
				},
				{
					id: 7,
					Segment: 'Government',
					Country: 'France',
					Product: ' Amarilla ',
					'Discount Band': ' None ',
					'Units Sold': '2750',
					'Manufacturing Price': ' $                260.00 ',
					'Sale Price': ' $           350.00 ',
					'Gross Sales': ' $      9,62,500.00 ',
					Discounts: ' $                     -   ',
					Sales: ' $               9,62,500.00 ',
					COGS: '',
					Profit: ' $                 2,47,500.00 ',
					Date: '2/1/14',
					'Month Number': '2',
					'Month Name': ' February ',
					Year: '2014'
				},
				{
					id: 8,
					Segment: 'Channel Partners',
					Country: 'United States of America',
					Product: ' Amarilla ',
					'Discount Band': ' None ',
					'Units Sold': '1953',
					'Manufacturing Price': ' $                260.00 ',
					'Sale Price': ' $              12.00 ',
					'Gross Sales': ' $          23,436.00 ',
					Discounts: ' $                     -   ',
					Sales: ' $                  23,436.00 ',
					COGS: ' $     5,859.00 ',
					Profit: ' $                    17,577.00 ',
					Date: '4/1/14',
					'Month Number': '4',
					'Month Name': ' April ',
					Year: '2014'
				},
				{
					id: 9,
					Segment: 'Enterprise',
					Country: 'Germany',
					Product: ' Amarilla ',
					'Discount Band': ' None ',
					'Units Sold': '4219.5',
					'Manufacturing Price': ' $                260.00 ',
					'Sale Price': ' $           125.00 ',
					'Gross Sales': ' $      5,27,437.50 ',
					Discounts: ' $                     -   ',
					Sales: ' $               5,27,437.50 ',
					COGS: '',
					Profit: ' $                    21,097.50 ',
					Date: '4/1/14',
					'Month Number': '4',
					'Month Name': ' April ',
					Year: '2014'
				},
				{
					id: 10,
					Segment: 'Government',
					Country: 'France',
					Product: ' Amarilla ',
					'Discount Band': ' None ',
					'Units Sold': '1899',
					'Manufacturing Price': ' $                260.00 ',
					'Sale Price': ' $              20.00 ',
					'Gross Sales': ' $          37,980.00 ',
					Discounts: ' $                     -   ',
					Sales: ' $                  37,980.00 ',
					COGS: ' $   18,990.00 ',
					Profit: ' $                    18,990.00 ',
					Date: '6/1/14',
					'Month Number': '6',
					'Month Name': ' June ',
					Year: '2014'
				},
				{
					id: 11,
					Segment: 'Government',
					Country: 'Germany',
					Product: ' Amarilla ',
					'Discount Band': ' None ',
					'Units Sold': '1686',
					'Manufacturing Price': ' $                260.00 ',
					'Sale Price': ' $                7.00 ',
					'Gross Sales': ' $          11,802.00 ',
					Discounts: ' $                     -   ',
					Sales: ' $                  11,802.00 ',
					COGS: ' $     8,430.00 ',
					Profit: ' $                       3,372.00 ',
					Date: '7/1/14',
					'Month Number': '7',
					'Month Name': ' July ',
					Year: '2014'
				},
				{
					id: 12,
					Segment: 'Channel Partners',
					Country: 'United States of America',
					Product: ' Amarilla ',
					'Discount Band': ' None ',
					'Units Sold': '2141',
					'Manufacturing Price': ' $                260.00 ',
					'Sale Price': ' $              12.00 ',
					'Gross Sales': ' $          25,692.00 ',
					Discounts: ' $                     -   ',
					Sales: ' $                  25,692.00 ',
					COGS: ' $     6,423.00 ',
					Profit: ' $                    19,269.00 ',
					Date: '8/1/14',
					'Month Number': '8',
					'Month Name': ' August ',
					Year: '2014'
				},
				{
					id: 13,
					Segment: 'Government',
					Country: 'United States of America',
					Product: ' Amarilla ',
					'Discount Band': ' None ',
					'Units Sold': '1143',
					'Manufacturing Price': ' $                260.00 ',
					'Sale Price': ' $                7.00 ',
					'Gross Sales': ' $            8,001.00 ',
					Discounts: ' $                     -   ',
					Sales: ' $                     8,001.00 ',
					COGS: ' $     5,715.00 ',
					Profit: ' $                       2,286.00 ',
					Date: '10/1/14',
					'Month Number': '10',
					'Month Name': ' October ',
					Year: '2014'
				},
				{
					id: 14,
					Segment: 'Midmarket',
					Country: 'United States of America',
					Product: ' Amarilla ',
					'Discount Band': ' None ',
					'Units Sold': '615',
					'Manufacturing Price': ' $                260.00 ',
					'Sale Price': ' $              15.00 ',
					'Gross Sales': ' $            9,225.00 ',
					Discounts: ' $                     -   ',
					Sales: ' $                     9,225.00 ',
					COGS: ' $     6,150.00 ',
					Profit: ' $                       3,075.00 ',
					Date: '12/1/14',
					'Month Number': '12',
					'Month Name': ' December ',
					Year: '2014'
				},
				{
					id: 15,
					Segment: 'Government',
					Country: 'France',
					Product: ' Paseo ',
					'Discount Band': ' Low ',
					'Units Sold': '3945',
					'Manufacturing Price': ' $                  10.00 ',
					'Sale Price': ' $                7.00 ',
					'Gross Sales': ' $          27,615.00 ',
					Discounts: ' $           276.15 ',
					Sales: ' $                  27,338.85 ',
					COGS: ' $   19,725.00 ',
					Profit: ' $                       7,613.85 ',
					Date: '1/1/14',
					'Month Number': '1',
					'Month Name': ' January ',
					Year: '2014'
				},
				{
					id: 16,
					Segment: 'Midmarket',
					Country: 'France',
					Product: ' Paseo ',
					'Discount Band': ' Low ',
					'Units Sold': '2296',
					'Manufacturing Price': ' $                  10.00 ',
					'Sale Price': ' $              15.00 ',
					'Gross Sales': ' $          34,440.00 ',
					Discounts: ' $           344.40 ',
					Sales: ' $                  34,095.60 ',
					COGS: ' $   22,960.00 ',
					Profit: ' $                    11,135.60 ',
					Date: '2/1/14',
					'Month Number': '2',
					'Month Name': ' February ',
					Year: '2014'
				},
				{
					id: 17,
					Segment: 'Government',
					Country: 'France',
					Product: ' Paseo ',
					'Discount Band': ' Low ',
					'Units Sold': '1030',
					'Manufacturing Price': ' $                  10.00 ',
					'Sale Price': ' $                7.00 ',
					'Gross Sales': ' $            7,210.00 ',
					Discounts: ' $              72.10 ',
					Sales: ' $                     7,137.90 ',
					COGS: ' $     5,150.00 ',
					Profit: ' $                       1,987.90 ',
					Date: '5/1/14',
					'Month Number': '5',
					'Month Name': ' May ',
					Year: '2014'
				},
				{
					id: 18,
					Segment: 'Government',
					Country: 'France',
					Product: ' Velo ',
					'Discount Band': ' Low ',
					'Units Sold': '639',
					'Manufacturing Price': ' $                120.00 ',
					'Sale Price': ' $                7.00 ',
					'Gross Sales': ' $            4,473.00 ',
					Discounts: ' $              44.73 ',
					Sales: ' $                     4,428.27 ',
					COGS: ' $     3,195.00 ',
					Profit: ' $                       1,233.27 ',
					Date: '11/1/14',
					'Month Number': '11',
					'Month Name': ' November ',
					Year: '2014'
				},
				{
					id: 19,
					Segment: 'Government',
					Country: 'Canada',
					Product: ' VTT ',
					'Discount Band': ' Low ',
					'Units Sold': '1326',
					'Manufacturing Price': ' $                250.00 ',
					'Sale Price': ' $                7.00 ',
					'Gross Sales': ' $            9,282.00 ',
					Discounts: ' $              92.82 ',
					Sales: ' $                     9,189.18 ',
					COGS: ' $     6,630.00 ',
					Profit: ' $                       2,559.18 ',
					Date: '3/1/14',
					'Month Number': '3',
					'Month Name': ' March ',
					Year: '2014'
				},
				{
					id: 20,
					Segment: 'Channel Partners',
					Country: 'United States of America',
					Product: ' Carretera ',
					'Discount Band': ' Low ',
					'Units Sold': '1858',
					'Manufacturing Price': ' $                     3.00 ',
					'Sale Price': ' $              12.00 ',
					'Gross Sales': ' $          22,296.00 ',
					Discounts: ' $           222.96 ',
					Sales: ' $                  22,073.04 ',
					COGS: ' $     5,574.00 ',
					Profit: ' $                    16,499.04 ',
					Date: '2/1/14',
					'Month Number': '2',
					'Month Name': ' February ',
					Year: '2014'
				},
				{
					id: 21,
					Segment: 'Government',
					Country: 'Mexico',
					Product: ' Carretera ',
					'Discount Band': ' Low ',
					'Units Sold': '1210',
					'Manufacturing Price': ' $                     3.00 ',
					'Sale Price': ' $           350.00 ',
					'Gross Sales': ' $      4,23,500.00 ',
					Discounts: ' $        4,235.00 ',
					Sales: ' $               4,19,265.00 ',
					COGS: '',
					Profit: ' $                 1,04,665.00 ',
					Date: '3/1/14',
					'Month Number': '3',
					'Month Name': ' March ',
					Year: '2014'
				},
				{
					id: 22,
					Segment: 'Government',
					Country: 'United States of America',
					Product: ' Carretera ',
					'Discount Band': ' Low ',
					'Units Sold': '2529',
					'Manufacturing Price': ' $                     3.00 ',
					'Sale Price': ' $                7.00 ',
					'Gross Sales': ' $          17,703.00 ',
					Discounts: ' $           177.03 ',
					Sales: ' $                  17,525.97 ',
					COGS: ' $   12,645.00 ',
					Profit: ' $                       4,880.97 ',
					Date: '7/1/14',
					'Month Number': '7',
					'Month Name': ' July ',
					Year: '2014'
				},
				{
					id: 23,
					Segment: 'Channel Partners',
					Country: 'Canada',
					Product: ' Carretera ',
					'Discount Band': ' Low ',
					'Units Sold': '1445',
					'Manufacturing Price': ' $                     3.00 ',
					'Sale Price': ' $              12.00 ',
					'Gross Sales': ' $          17,340.00 ',
					Discounts: ' $           173.40 ',
					Sales: ' $                  17,166.60 ',
					COGS: ' $     4,335.00 ',
					Profit: ' $                    12,831.60 ',
					Date: '9/1/14',
					'Month Number': '9',
					'Month Name': ' September ',
					Year: '2014'
				},
				{
					id: 24,
					Segment: 'Enterprise',
					Country: 'United States of America',
					Product: ' Carretera ',
					'Discount Band': ' Low ',
					'Units Sold': '330',
					'Manufacturing Price': ' $                     3.00 ',
					'Sale Price': ' $           125.00 ',
					'Gross Sales': ' $          41,250.00 ',
					Discounts: ' $           412.50 ',
					Sales: ' $                  40,837.50 ',
					COGS: ' $   39,600.00 ',
					Profit: ' $                       1,237.50 ',
					Date: '9/1/13',
					'Month Number': '9',
					'Month Name': ' September ',
					Year: '2013'
				},
				{
					id: 25,
					Segment: 'Channel Partners',
					Country: 'France',
					Product: ' Carretera ',
					'Discount Band': ' Low ',
					'Units Sold': '2671',
					'Manufacturing Price': ' $                     3.00 ',
					'Sale Price': ' $              12.00 ',
					'Gross Sales': ' $          32,052.00 ',
					Discounts: ' $           320.52 ',
					Sales: ' $                  31,731.48 ',
					COGS: ' $     8,013.00 ',
					Profit: ' $                    23,718.48 ',
					Date: '9/1/14',
					'Month Number': '9',
					'Month Name': ' September ',
					Year: '2014'
				},
				{
					id: 26,
					Segment: 'Channel Partners',
					Country: 'Germany',
					Product: ' Carretera ',
					'Discount Band': ' Low ',
					'Units Sold': '766',
					'Manufacturing Price': ' $                     3.00 ',
					'Sale Price': ' $              12.00 ',
					'Gross Sales': ' $            9,192.00 ',
					Discounts: ' $              91.92 ',
					Sales: ' $                     9,100.08 ',
					COGS: ' $     2,298.00 ',
					Profit: ' $                       6,802.08 ',
					Date: '10/1/13',
					'Month Number': '10',
					'Month Name': ' October ',
					Year: '2013'
				},
				{
					id: 27,
					Segment: 'Small Business',
					Country: 'Mexico',
					Product: ' Carretera ',
					'Discount Band': ' Low ',
					'Units Sold': '494',
					'Manufacturing Price': ' $                     3.00 ',
					'Sale Price': ' $           300.00 ',
					'Gross Sales': ' $      1,48,200.00 ',
					Discounts: ' $        1,482.00 ',
					Sales: ' $               1,46,718.00 ',
					COGS: '',
					Profit: ' $                    23,218.00 ',
					Date: '10/1/13',
					'Month Number': '10',
					'Month Name': ' October ',
					Year: '2013'
				},
				{
					id: 28,
					Segment: 'Government',
					Country: 'Mexico',
					Product: ' Carretera ',
					'Discount Band': ' Low ',
					'Units Sold': '1397',
					'Manufacturing Price': ' $                     3.00 ',
					'Sale Price': ' $           350.00 ',
					'Gross Sales': ' $      4,88,950.00 ',
					Discounts: ' $        4,889.50 ',
					Sales: ' $               4,84,060.50 ',
					COGS: '',
					Profit: ' $                 1,20,840.50 ',
					Date: '10/1/14',
					'Month Number': '10',
					'Month Name': ' October ',
					Year: '2014'
				},
				{
					id: 29,
					Segment: 'Government',
					Country: 'France',
					Product: ' Carretera ',
					'Discount Band': ' Low ',
					'Units Sold': '2155',
					'Manufacturing Price': ' $                     3.00 ',
					'Sale Price': ' $           350.00 ',
					'Gross Sales': ' $      7,54,250.00 ',
					Discounts: ' $        7,542.50 ',
					Sales: ' $               7,46,707.50 ',
					COGS: '',
					Profit: ' $                 1,86,407.50 ',
					Date: '12/1/14',
					'Month Number': '12',
					'Month Name': ' December ',
					Year: '2014'
				},
				{
					id: 30,
					Segment: 'Midmarket',
					Country: 'Mexico',
					Product: ' Montana ',
					'Discount Band': ' Low ',
					'Units Sold': '2214',
					'Manufacturing Price': ' $                     5.00 ',
					'Sale Price': ' $              15.00 ',
					'Gross Sales': ' $          33,210.00 ',
					Discounts: ' $           332.10 ',
					Sales: ' $                  32,877.90 ',
					COGS: ' $   22,140.00 ',
					Profit: ' $                    10,737.90 ',
					Date: '3/1/14',
					'Month Number': '3',
					'Month Name': ' March ',
					Year: '2014'
				},
				{
					id: 31,
					Segment: 'Small Business',
					Country: 'United States of America',
					Product: ' Montana ',
					'Discount Band': ' Low ',
					'Units Sold': '2301',
					'Manufacturing Price': ' $                     5.00 ',
					'Sale Price': ' $           300.00 ',
					'Gross Sales': ' $      6,90,300.00 ',
					Discounts: ' $        6,903.00 ',
					Sales: ' $               6,83,397.00 ',
					COGS: '',
					Profit: ' $                 1,08,147.00 ',
					Date: '4/1/14',
					'Month Number': '4',
					'Month Name': ' April ',
					Year: '2014'
				},
				{
					id: 32,
					Segment: 'Government',
					Country: 'France',
					Product: ' Montana ',
					'Discount Band': ' Low ',
					'Units Sold': '1375.5',
					'Manufacturing Price': ' $                     5.00 ',
					'Sale Price': ' $              20.00 ',
					'Gross Sales': ' $          27,510.00 ',
					Discounts: ' $           275.10 ',
					Sales: ' $                  27,234.90 ',
					COGS: ' $   13,755.00 ',
					Profit: ' $                    13,479.90 ',
					Date: '7/1/14',
					'Month Number': '7',
					'Month Name': ' July ',
					Year: '2014'
				},
				{
					id: 33,
					Segment: 'Government',
					Country: 'Canada',
					Product: ' Montana ',
					'Discount Band': ' Low ',
					'Units Sold': '1830',
					'Manufacturing Price': ' $                     5.00 ',
					'Sale Price': ' $                7.00 ',
					'Gross Sales': ' $          12,810.00 ',
					Discounts: ' $           128.10 ',
					Sales: ' $                  12,681.90 ',
					COGS: ' $     9,150.00 ',
					Profit: ' $                       3,531.90 ',
					Date: '8/1/14',
					'Month Number': '8',
					'Month Name': ' August ',
					Year: '2014'
				},
				{
					id: 34,
					Segment: 'Small Business',
					Country: 'United States of America',
					Product: ' Montana ',
					'Discount Band': ' Low ',
					'Units Sold': '2498',
					'Manufacturing Price': ' $                     5.00 ',
					'Sale Price': ' $           300.00 ',
					'Gross Sales': ' $      7,49,400.00 ',
					Discounts: ' $        7,494.00 ',
					Sales: ' $               7,41,906.00 ',
					COGS: '',
					Profit: ' $                 1,17,406.00 ',
					Date: '9/1/13',
					'Month Number': '9',
					'Month Name': ' September ',
					Year: '2013'
				},
				{
					id: 35,
					Segment: 'Enterprise',
					Country: 'United States of America',
					Product: ' Montana ',
					'Discount Band': ' Low ',
					'Units Sold': '663',
					'Manufacturing Price': ' $                     5.00 ',
					'Sale Price': ' $           125.00 ',
					'Gross Sales': ' $          82,875.00 ',
					Discounts: ' $           828.75 ',
					Sales: ' $                  82,046.25 ',
					COGS: ' $   79,560.00 ',
					Profit: ' $                       2,486.25 ',
					Date: '10/1/13',
					'Month Number': '10',
					'Month Name': ' October ',
					Year: '2013'
				},
				{
					id: 36,
					Segment: 'Midmarket',
					Country: 'United States of America',
					Product: ' Paseo ',
					'Discount Band': ' Low ',
					'Units Sold': '1514',
					'Manufacturing Price': ' $                  10.00 ',
					'Sale Price': ' $              15.00 ',
					'Gross Sales': ' $          22,710.00 ',
					Discounts: ' $           227.10 ',
					Sales: ' $                  22,482.90 ',
					COGS: ' $   15,140.00 ',
					Profit: ' $                       7,342.90 ',
					Date: '2/1/14',
					'Month Number': '2',
					'Month Name': ' February ',
					Year: '2014'
				},
				{
					id: 37,
					Segment: 'Government',
					Country: 'United States of America',
					Product: ' Paseo ',
					'Discount Band': ' Low ',
					'Units Sold': '4492.5',
					'Manufacturing Price': ' $                  10.00 ',
					'Sale Price': ' $                7.00 ',
					'Gross Sales': ' $          31,447.50 ',
					Discounts: ' $           314.48 ',
					Sales: ' $                  31,133.03 ',
					COGS: ' $   22,462.50 ',
					Profit: ' $                       8,670.53 ',
					Date: '4/1/14',
					'Month Number': '4',
					'Month Name': ' April ',
					Year: '2014'
				},
				{
					id: 38,
					Segment: 'Enterprise',
					Country: 'United States of America',
					Product: ' Paseo ',
					'Discount Band': ' Low ',
					'Units Sold': '727',
					'Manufacturing Price': ' $                  10.00 ',
					'Sale Price': ' $           125.00 ',
					'Gross Sales': ' $          90,875.00 ',
					Discounts: ' $           908.75 ',
					Sales: ' $                  89,966.25 ',
					COGS: ' $   87,240.00 ',
					Profit: ' $                       2,726.25 ',
					Date: '6/1/14',
					'Month Number': '6',
					'Month Name': ' June ',
					Year: '2014'
				},
				{
					id: 39,
					Segment: 'Enterprise',
					Country: 'France',
					Product: ' Paseo ',
					'Discount Band': ' Low ',
					'Units Sold': '787',
					'Manufacturing Price': ' $                  10.00 ',
					'Sale Price': ' $           125.00 ',
					'Gross Sales': ' $          98,375.00 ',
					Discounts: ' $           983.75 ',
					Sales: ' $                  97,391.25 ',
					COGS: ' $   94,440.00 ',
					Profit: ' $                       2,951.25 ',
					Date: '6/1/14',
					'Month Number': '6',
					'Month Name': ' June ',
					Year: '2014'
				},
				{
					id: 40,
					Segment: 'Enterprise',
					Country: 'Mexico',
					Product: ' Paseo ',
					'Discount Band': ' Low ',
					'Units Sold': '1823',
					'Manufacturing Price': ' $                  10.00 ',
					'Sale Price': ' $           125.00 ',
					'Gross Sales': ' $      2,27,875.00 ',
					Discounts: ' $        2,278.75 ',
					Sales: ' $               2,25,596.25 ',
					COGS: '',
					Profit: ' $                       6,836.25 ',
					Date: '7/1/14',
					'Month Number': '7',
					'Month Name': ' July ',
					Year: '2014'
				}
			],
			position: {
				w: 4,
				x: 0,
				h: 4,
				y: 0
			}
		}
	],
	type_id: 2,
	name: 'Sample Report',
	id: 3,
	filters: [
		{
			filter_id: 1,
			allowed_values: ['NA', 'SEA', 'MEA', 'APJ', 'India and Subcontinent'],
			min: null,
			max: null,
			filter_type: 'drop-down',
			filter_name: 'region',
			default_value: 'NA'
		},
		{
			filter_id: 2,
			allowed_values: ['Enterprise', 'SME typ'],
			min: null,
			max: null,
			filter_type: 'drop-down',
			filter_name: 'type',
			default_value: null
		},
		{
			filter_id: 3,
			allowed_values: [
				'Retail',
				'E-commerce',
				'Manufacturing & CPG/FMCG',
				'Industrial Services',
				'3PL & CEP',
				'E-grocery',
				'Others',
				'Home Services'
			],
			min: null,
			max: null,
			filter_type: 'drop-down',
			filter_name: 'industry',
			default_value: null
		},
		{
			filter_id: 4,
			allowed_values: [
				{
					name: 'Sep 2021',
					startDate: '20220901',
					endDate: '20221001',
					asof: '20221001'
				},
				{
					name: 'Oct 2021',
					startDate: '20221001',
					endDate: '20221101',
					asof: '20221101'
				},
				{
					name: 'Nov 2021',
					startDate: '20221101',
					endDate: '20221201',
					asof: '20221201'
				},
				{
					name: 'Dec 2021',
					startDate: '20221201',
					endDate: '20230101',
					asof: '20230101'
				}
			],
			min: null,
			max: null,
			filter_type: 'drop-down',
			filter_name: 'month',
			default_value: 'Sep 2021'
		}
	],
	type: 'report',
	object_id: 3,
	config: {
		customer: 'Alex Cross',
		items: {
			product: 'Tea',
			qty: 6
		}
	}
};
